version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "9090:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mydb-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mydb-data:

networks:
  app-network:
