spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}/${DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #    open-in-view: false
  #        dialect: org.hibernate.dialect.MySQLDialect
  #  profiles:
  #    active: docker
  task:
    scheduling:
      pool:
        size: 10
      shutdown:
        await-termination: true
        await-termination-period: 30s
#  retry:
#    enabled: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
